# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0cImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\rImageResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32i\n\x04Pyuo\x12\x30\n\x05Reset\x12\x12.test.ImageRequest\x1a\x13.test.ImageResponse\x12/\n\x04Step\x12\x12.test.ImageRequest\x1a\x13.test.ImageResponseb\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_IMAGERESPONSE = DESCRIPTOR.message_types_by_name['ImageResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

_PYUO = DESCRIPTOR.services_by_name['Pyuo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=20
  _HELLOREQUEST._serialized_end=48
  _HELLOREPLY._serialized_start=50
  _HELLOREPLY._serialized_end=79
  _IMAGEREQUEST._serialized_start=81
  _IMAGEREQUEST._serialized_end=109
  _IMAGERESPONSE._serialized_start=111
  _IMAGERESPONSE._serialized_end=140
  _PYUO._serialized_start=142
  _PYUO._serialized_end=247
# @@protoc_insertion_point(module_scope)
