# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import UoService_pb2 as UoService__pb2


class UoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reset = channel.unary_unary(
                '/uoservice.UoService/reset',
                request_serializer=UoService__pb2.ImageRequest.SerializeToString,
                response_deserializer=UoService__pb2.ImageResponse.FromString,
                )
        self.step = channel.unary_unary(
                '/uoservice.UoService/step',
                request_serializer=UoService__pb2.ImageRequest.SerializeToString,
                response_deserializer=UoService__pb2.ImageResponse.FromString,
                )
        self.act = channel.unary_unary(
                '/uoservice.UoService/act',
                request_serializer=UoService__pb2.Actions.SerializeToString,
                response_deserializer=UoService__pb2.Empty.FromString,
                )


class UoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def act(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reset': grpc.unary_unary_rpc_method_handler(
                    servicer.reset,
                    request_deserializer=UoService__pb2.ImageRequest.FromString,
                    response_serializer=UoService__pb2.ImageResponse.SerializeToString,
            ),
            'step': grpc.unary_unary_rpc_method_handler(
                    servicer.step,
                    request_deserializer=UoService__pb2.ImageRequest.FromString,
                    response_serializer=UoService__pb2.ImageResponse.SerializeToString,
            ),
            'act': grpc.unary_unary_rpc_method_handler(
                    servicer.act,
                    request_deserializer=UoService__pb2.Actions.FromString,
                    response_serializer=UoService__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uoservice.UoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uoservice.UoService/reset',
            UoService__pb2.ImageRequest.SerializeToString,
            UoService__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uoservice.UoService/step',
            UoService__pb2.ImageRequest.SerializeToString,
            UoService__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def act(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/uoservice.UoService/act',
            UoService__pb2.Actions.SerializeToString,
            UoService__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
