# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UoService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fUoService.proto\x12\tuoservice\"\x07\n\x05\x45mpty\"\x1c\n\x0cImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\rImageResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x19\n\x07\x41\x63tions\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\r2\xaf\x01\n\tUoService\x12:\n\x05reset\x12\x17.uoservice.ImageRequest\x1a\x18.uoservice.ImageResponse\x12\x39\n\x04step\x12\x17.uoservice.ImageRequest\x1a\x18.uoservice.ImageResponse\x12+\n\x03\x61\x63t\x12\x12.uoservice.Actions\x1a\x10.uoservice.Emptyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_IMAGERESPONSE = DESCRIPTOR.message_types_by_name['ImageResponse']
_ACTIONS = DESCRIPTOR.message_types_by_name['Actions']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONS,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.Actions)
  })
_sym_db.RegisterMessage(Actions)

_UOSERVICE = DESCRIPTOR.services_by_name['UoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=30
  _EMPTY._serialized_end=37
  _IMAGEREQUEST._serialized_start=39
  _IMAGEREQUEST._serialized_end=67
  _IMAGERESPONSE._serialized_start=69
  _IMAGERESPONSE._serialized_end=98
  _ACTIONS._serialized_start=100
  _ACTIONS._serialized_end=125
  _UOSERVICE._serialized_start=128
  _UOSERVICE._serialized_end=303
# @@protoc_insertion_point(module_scope)
