// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UoService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Uoservice {
  public static partial class UoService
  {
    static readonly string __ServiceName = "uoservice.UoService";

    static readonly grpc::Marshaller<global::Uoservice.ImageRequest> __Marshaller_uoservice_ImageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Uoservice.ImageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Uoservice.ImageResponse> __Marshaller_uoservice_ImageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Uoservice.ImageResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse> __Method_Reset = new grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Reset",
        __Marshaller_uoservice_ImageRequest,
        __Marshaller_uoservice_ImageResponse);

    static readonly grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse> __Method_Step = new grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Step",
        __Marshaller_uoservice_ImageRequest,
        __Marshaller_uoservice_ImageResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Uoservice.UoServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UoService</summary>
    public abstract partial class UoServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Uoservice.ImageResponse> Reset(global::Uoservice.ImageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Uoservice.ImageResponse> Step(global::Uoservice.ImageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UoService</summary>
    public partial class UoServiceClient : grpc::ClientBase<UoServiceClient>
    {
      /// <summary>Creates a new client for UoService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UoServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UoService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UoServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UoServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UoServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Uoservice.ImageResponse Reset(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Reset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Uoservice.ImageResponse Reset(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Reset, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> ResetAsync(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ResetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> ResetAsync(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Reset, null, options, request);
      }
      public virtual global::Uoservice.ImageResponse Step(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Step(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Uoservice.ImageResponse Step(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Step, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> StepAsync(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StepAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> StepAsync(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Step, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UoServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UoServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UoServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Reset, serviceImpl.Reset)
          .AddMethod(__Method_Step, serviceImpl.Step).Build();
    }

  }
}
#endregion
