# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UoService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fUoService.proto\x12\tuoservice\"\x07\n\x05\x45mpty\"R\n\x0eGrpcMobileData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x0c\n\x04race\x18\x04 \x01(\r\x12\x0e\n\x06serial\x18\x05 \x01(\r\"\x1f\n\x0fSemaphoreAction\x12\x0c\n\x04mode\x18\x01 \x01(\t\";\n\x0eGrpcMobileList\x12)\n\x06mobile\x18\x01 \x03(\x0b\x32\x19.uoservice.GrpcMobileData\"\x1c\n\x0cImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0bScreenImage\x12\r\n\x05image\x18\x01 \x01(\x0c\"d\n\x06States\x12+\n\x0bscreenImage\x18\x01 \x01(\x0b\x32\x16.uoservice.ScreenImage\x12-\n\nmobileList\x18\x02 \x01(\x0b\x32\x19.uoservice.GrpcMobileList\"\"\n\nMousePoint\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\"T\n\x07\x41\x63tions\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\r\x12)\n\nmousePoint\x18\x02 \x01(\x0b\x32\x15.uoservice.MousePoint\x12\x0e\n\x06serial\x18\x03 \x01(\r2\xb3\x02\n\tUoService\x12\x33\n\x05Reset\x12\x17.uoservice.ImageRequest\x1a\x11.uoservice.States\x12\x35\n\x07ReadObs\x12\x17.uoservice.ImageRequest\x1a\x11.uoservice.States\x12\x30\n\x08WriteAct\x12\x12.uoservice.Actions\x1a\x10.uoservice.Empty\x12\x43\n\x13\x41\x63tSemaphoreControl\x12\x1a.uoservice.SemaphoreAction\x1a\x10.uoservice.Empty\x12\x43\n\x13ObsSemaphoreControl\x12\x1a.uoservice.SemaphoreAction\x1a\x10.uoservice.Emptyb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_GRPCMOBILEDATA = DESCRIPTOR.message_types_by_name['GrpcMobileData']
_SEMAPHOREACTION = DESCRIPTOR.message_types_by_name['SemaphoreAction']
_GRPCMOBILELIST = DESCRIPTOR.message_types_by_name['GrpcMobileList']
_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_SCREENIMAGE = DESCRIPTOR.message_types_by_name['ScreenImage']
_STATES = DESCRIPTOR.message_types_by_name['States']
_MOUSEPOINT = DESCRIPTOR.message_types_by_name['MousePoint']
_ACTIONS = DESCRIPTOR.message_types_by_name['Actions']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

GrpcMobileData = _reflection.GeneratedProtocolMessageType('GrpcMobileData', (_message.Message,), {
  'DESCRIPTOR' : _GRPCMOBILEDATA,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.GrpcMobileData)
  })
_sym_db.RegisterMessage(GrpcMobileData)

SemaphoreAction = _reflection.GeneratedProtocolMessageType('SemaphoreAction', (_message.Message,), {
  'DESCRIPTOR' : _SEMAPHOREACTION,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.SemaphoreAction)
  })
_sym_db.RegisterMessage(SemaphoreAction)

GrpcMobileList = _reflection.GeneratedProtocolMessageType('GrpcMobileList', (_message.Message,), {
  'DESCRIPTOR' : _GRPCMOBILELIST,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.GrpcMobileList)
  })
_sym_db.RegisterMessage(GrpcMobileList)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ScreenImage = _reflection.GeneratedProtocolMessageType('ScreenImage', (_message.Message,), {
  'DESCRIPTOR' : _SCREENIMAGE,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.ScreenImage)
  })
_sym_db.RegisterMessage(ScreenImage)

States = _reflection.GeneratedProtocolMessageType('States', (_message.Message,), {
  'DESCRIPTOR' : _STATES,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.States)
  })
_sym_db.RegisterMessage(States)

MousePoint = _reflection.GeneratedProtocolMessageType('MousePoint', (_message.Message,), {
  'DESCRIPTOR' : _MOUSEPOINT,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.MousePoint)
  })
_sym_db.RegisterMessage(MousePoint)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONS,
  '__module__' : 'UoService_pb2'
  # @@protoc_insertion_point(class_scope:uoservice.Actions)
  })
_sym_db.RegisterMessage(Actions)

_UOSERVICE = DESCRIPTOR.services_by_name['UoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=30
  _EMPTY._serialized_end=37
  _GRPCMOBILEDATA._serialized_start=39
  _GRPCMOBILEDATA._serialized_end=121
  _SEMAPHOREACTION._serialized_start=123
  _SEMAPHOREACTION._serialized_end=154
  _GRPCMOBILELIST._serialized_start=156
  _GRPCMOBILELIST._serialized_end=215
  _IMAGEREQUEST._serialized_start=217
  _IMAGEREQUEST._serialized_end=245
  _SCREENIMAGE._serialized_start=247
  _SCREENIMAGE._serialized_end=275
  _STATES._serialized_start=277
  _STATES._serialized_end=377
  _MOUSEPOINT._serialized_start=379
  _MOUSEPOINT._serialized_end=413
  _ACTIONS._serialized_start=415
  _ACTIONS._serialized_end=499
  _UOSERVICE._serialized_start=502
  _UOSERVICE._serialized_end=809
# @@protoc_insertion_point(module_scope)
