// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UoService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Uoservice {

  /// <summary>Holder for reflection information generated from UoService.proto</summary>
  public static partial class UoServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for UoService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UoServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Vb1NlcnZpY2UucHJvdG8SCXVvc2VydmljZSIHCgVFbXB0eSJSCg5HcnBj",
            "TW9iaWxlRGF0YRIMCgRuYW1lGAEgASgJEgkKAXgYAiABKAISCQoBeRgDIAEo",
            "AhIMCgRyYWNlGAQgASgNEg4KBnNlcmlhbBgFIAEoDSJLCgxHcnBjSXRlbURh",
            "dGESDAoEbmFtZRgBIAEoCRINCgVsYXllchgCIAEoDRIOCgZzZXJpYWwYAyAB",
            "KA0SDgoGYW1vdW50GAQgASgNIqQBChJHcnBjR2FtZU9iamVjdERhdGESDAoE",
            "dHlwZRgBIAEoCRIPCgdzY3JlZW5YGAIgASgNEg8KB3NjcmVlblkYAyABKA0S",
            "EAoIZGlzdGFuY2UYBCABKA0SDQoFZ2FtZVgYBSABKA0SDQoFZ2FtZVkYBiAB",
            "KA0SDgoGc2VyaWFsGAcgASgNEgwKBG5hbWUYCCABKAkSEAoIaXNDb3Jwc2UY",
            "CSABKAgiRwoSR3JwY0dhbWVPYmplY3RMaXN0EjEKCmdhbWVPYmplY3QYASAD",
            "KAsyHS51b3NlcnZpY2UuR3JwY0dhbWVPYmplY3REYXRhIh8KD1NlbWFwaG9y",
            "ZUFjdGlvbhIMCgRtb2RlGAEgASgJIjsKDkdycGNNb2JpbGVMaXN0EikKBm1v",
            "YmlsZRgBIAMoCzIZLnVvc2VydmljZS5HcnBjTW9iaWxlRGF0YSI1CgxHcnBj",
            "SXRlbUxpc3QSJQoEaXRlbRgBIAMoCzIXLnVvc2VydmljZS5HcnBjSXRlbURh",
            "dGEiFgoGQ29uZmlnEgwKBG5hbWUYASABKAki6AEKDFBsYXllclN0YXR1cxIL",
            "CgNzdHIYASABKA0SCwoDZGV4GAIgASgNEg4KBmludGVsbBgDIAEoDRIMCgRo",
            "aXRzGAQgASgNEg8KB2hpdHNNYXgYBSABKA0SDwoHc3RhbWluYRgGIAEoDRIS",
            "CgpzdGFtaW5hTWF4GAcgASgNEgwKBG1hbmEYCCABKA0SDwoHbWFuYU1heBgJ",
            "IAEoDRIMCgRnb2xkGAogASgNEhoKEnBoeXNpY2FsUmVzaXN0YW5jZRgLIAEo",
            "DRIOCgZ3ZWlnaHQYDCABKA0SEQoJd2VpZ2h0TWF4GA0gASgNItgECgZTdGF0",
            "ZXMSLQoKbW9iaWxlTGlzdBgBIAEoCzIZLnVvc2VydmljZS5HcnBjTW9iaWxl",
            "TGlzdBIuCg13b3JsZEl0ZW1MaXN0GAIgASgLMhcudW9zZXJ2aWNlLkdycGNJ",
            "dGVtTGlzdBIxChBlcXVpcHBlZEl0ZW1MaXN0GAMgASgLMhcudW9zZXJ2aWNl",
            "LkdycGNJdGVtTGlzdBIxChBiYWNrcGFja0l0ZW1MaXN0GAQgASgLMhcudW9z",
            "ZXJ2aWNlLkdycGNJdGVtTGlzdBItCgxwbGF5ZXJTdGF0dXMYBSABKAsyFy51",
            "b3NlcnZpY2UuUGxheWVyU3RhdHVzEjcKEG1vYmlsZU9iamVjdExpc3QYBiAB",
            "KAsyHS51b3NlcnZpY2UuR3JwY0dhbWVPYmplY3RMaXN0Ej0KFnBsYXllck1v",
            "YmlsZU9iamVjdExpc3QYByABKAsyHS51b3NlcnZpY2UuR3JwY0dhbWVPYmpl",
            "Y3RMaXN0EjUKDmxhbmRPYmplY3RMaXN0GAggASgLMh0udW9zZXJ2aWNlLkdy",
            "cGNHYW1lT2JqZWN0TGlzdBI1Cg5pdGVtT2JqZWN0TGlzdBgJIAEoCzIdLnVv",
            "c2VydmljZS5HcnBjR2FtZU9iamVjdExpc3QSNwoQc3RhdGljT2JqZWN0TGlz",
            "dBgKIAEoCzIdLnVvc2VydmljZS5HcnBjR2FtZU9iamVjdExpc3QSOwoUaXRl",
            "bURyb3BhYmxlTGFuZExpc3QYCyABKAsyHS51b3NlcnZpY2UuR3JwY0dhbWVP",
            "YmplY3RMaXN0IiIKDVdhbGtEaXJlY3Rpb24SEQoJZGlyZWN0aW9uGAEgASgN",
            "IngKB0FjdGlvbnMSEgoKYWN0aW9uVHlwZRgBIAEoDRIUCgxtb2JpbGVTZXJp",
            "YWwYAiABKA0SEgoKaXRlbVNlcmlhbBgDIAEoDRIvCg13YWxrRGlyZWN0aW9u",
            "GAQgASgLMhgudW9zZXJ2aWNlLldhbGtEaXJlY3Rpb24ypwIKCVVvU2Vydmlj",
            "ZRItCgVSZXNldBIRLnVvc2VydmljZS5Db25maWcaES51b3NlcnZpY2UuU3Rh",
            "dGVzEi8KB1JlYWRPYnMSES51b3NlcnZpY2UuQ29uZmlnGhEudW9zZXJ2aWNl",
            "LlN0YXRlcxIwCghXcml0ZUFjdBISLnVvc2VydmljZS5BY3Rpb25zGhAudW9z",
            "ZXJ2aWNlLkVtcHR5EkMKE0FjdFNlbWFwaG9yZUNvbnRyb2wSGi51b3NlcnZp",
            "Y2UuU2VtYXBob3JlQWN0aW9uGhAudW9zZXJ2aWNlLkVtcHR5EkMKE09ic1Nl",
            "bWFwaG9yZUNvbnRyb2wSGi51b3NlcnZpY2UuU2VtYXBob3JlQWN0aW9uGhAu",
            "dW9zZXJ2aWNlLkVtcHR5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.Empty), global::Uoservice.Empty.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.GrpcMobileData), global::Uoservice.GrpcMobileData.Parser, new[]{ "Name", "X", "Y", "Race", "Serial" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.GrpcItemData), global::Uoservice.GrpcItemData.Parser, new[]{ "Name", "Layer", "Serial", "Amount" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.GrpcGameObjectData), global::Uoservice.GrpcGameObjectData.Parser, new[]{ "Type", "ScreenX", "ScreenY", "Distance", "GameX", "GameY", "Serial", "Name", "IsCorpse" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.GrpcGameObjectList), global::Uoservice.GrpcGameObjectList.Parser, new[]{ "GameObject" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.SemaphoreAction), global::Uoservice.SemaphoreAction.Parser, new[]{ "Mode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.GrpcMobileList), global::Uoservice.GrpcMobileList.Parser, new[]{ "Mobile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.GrpcItemList), global::Uoservice.GrpcItemList.Parser, new[]{ "Item" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.Config), global::Uoservice.Config.Parser, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.PlayerStatus), global::Uoservice.PlayerStatus.Parser, new[]{ "Str", "Dex", "Intell", "Hits", "HitsMax", "Stamina", "StaminaMax", "Mana", "ManaMax", "Gold", "PhysicalResistance", "Weight", "WeightMax" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.States), global::Uoservice.States.Parser, new[]{ "MobileList", "WorldItemList", "EquippedItemList", "BackpackItemList", "PlayerStatus", "MobileObjectList", "PlayerMobileObjectList", "LandObjectList", "ItemObjectList", "StaticObjectList", "ItemDropableLandList" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.WalkDirection), global::Uoservice.WalkDirection.Parser, new[]{ "Direction" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Uoservice.Actions), global::Uoservice.Actions.Parser, new[]{ "ActionType", "MobileSerial", "ItemSerial", "WalkDirection" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Empty : pb::IMessage<Empty> {
    private static readonly pb::MessageParser<Empty> _parser = new pb::MessageParser<Empty>(() => new Empty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Empty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty(Empty other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Empty Clone() {
      return new Empty(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Empty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Empty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Empty other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GrpcMobileData : pb::IMessage<GrpcMobileData> {
    private static readonly pb::MessageParser<GrpcMobileData> _parser = new pb::MessageParser<GrpcMobileData>(() => new GrpcMobileData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcMobileData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcMobileData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcMobileData(GrpcMobileData other) : this() {
      name_ = other.name_;
      x_ = other.x_;
      y_ = other.y_;
      race_ = other.race_;
      serial_ = other.serial_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcMobileData Clone() {
      return new GrpcMobileData(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 2;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 3;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "race" field.</summary>
    public const int RaceFieldNumber = 4;
    private uint race_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Race {
      get { return race_; }
      set {
        race_ = value;
      }
    }

    /// <summary>Field number for the "serial" field.</summary>
    public const int SerialFieldNumber = 5;
    private uint serial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Serial {
      get { return serial_; }
      set {
        serial_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcMobileData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcMobileData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (Race != other.Race) return false;
      if (Serial != other.Serial) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Race != 0) hash ^= Race.GetHashCode();
      if (Serial != 0) hash ^= Serial.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (X != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Y);
      }
      if (Race != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Race);
      }
      if (Serial != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Serial);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Race != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Race);
      }
      if (Serial != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Serial);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcMobileData other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Race != 0) {
        Race = other.Race;
      }
      if (other.Serial != 0) {
        Serial = other.Serial;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 21: {
            X = input.ReadFloat();
            break;
          }
          case 29: {
            Y = input.ReadFloat();
            break;
          }
          case 32: {
            Race = input.ReadUInt32();
            break;
          }
          case 40: {
            Serial = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcItemData : pb::IMessage<GrpcItemData> {
    private static readonly pb::MessageParser<GrpcItemData> _parser = new pb::MessageParser<GrpcItemData>(() => new GrpcItemData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcItemData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcItemData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcItemData(GrpcItemData other) : this() {
      name_ = other.name_;
      layer_ = other.layer_;
      serial_ = other.serial_;
      amount_ = other.amount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcItemData Clone() {
      return new GrpcItemData(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "layer" field.</summary>
    public const int LayerFieldNumber = 2;
    private uint layer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Layer {
      get { return layer_; }
      set {
        layer_ = value;
      }
    }

    /// <summary>Field number for the "serial" field.</summary>
    public const int SerialFieldNumber = 3;
    private uint serial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Serial {
      get { return serial_; }
      set {
        serial_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 4;
    private uint amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcItemData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcItemData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Layer != other.Layer) return false;
      if (Serial != other.Serial) return false;
      if (Amount != other.Amount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Layer != 0) hash ^= Layer.GetHashCode();
      if (Serial != 0) hash ^= Serial.GetHashCode();
      if (Amount != 0) hash ^= Amount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Layer != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Layer);
      }
      if (Serial != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Serial);
      }
      if (Amount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Layer != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Layer);
      }
      if (Serial != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Serial);
      }
      if (Amount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Amount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcItemData other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Layer != 0) {
        Layer = other.Layer;
      }
      if (other.Serial != 0) {
        Serial = other.Serial;
      }
      if (other.Amount != 0) {
        Amount = other.Amount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Layer = input.ReadUInt32();
            break;
          }
          case 24: {
            Serial = input.ReadUInt32();
            break;
          }
          case 32: {
            Amount = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcGameObjectData : pb::IMessage<GrpcGameObjectData> {
    private static readonly pb::MessageParser<GrpcGameObjectData> _parser = new pb::MessageParser<GrpcGameObjectData>(() => new GrpcGameObjectData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcGameObjectData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcGameObjectData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcGameObjectData(GrpcGameObjectData other) : this() {
      type_ = other.type_;
      screenX_ = other.screenX_;
      screenY_ = other.screenY_;
      distance_ = other.distance_;
      gameX_ = other.gameX_;
      gameY_ = other.gameY_;
      serial_ = other.serial_;
      name_ = other.name_;
      isCorpse_ = other.isCorpse_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcGameObjectData Clone() {
      return new GrpcGameObjectData(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "screenX" field.</summary>
    public const int ScreenXFieldNumber = 2;
    private uint screenX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ScreenX {
      get { return screenX_; }
      set {
        screenX_ = value;
      }
    }

    /// <summary>Field number for the "screenY" field.</summary>
    public const int ScreenYFieldNumber = 3;
    private uint screenY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ScreenY {
      get { return screenY_; }
      set {
        screenY_ = value;
      }
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 4;
    private uint distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "gameX" field.</summary>
    public const int GameXFieldNumber = 5;
    private uint gameX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint GameX {
      get { return gameX_; }
      set {
        gameX_ = value;
      }
    }

    /// <summary>Field number for the "gameY" field.</summary>
    public const int GameYFieldNumber = 6;
    private uint gameY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint GameY {
      get { return gameY_; }
      set {
        gameY_ = value;
      }
    }

    /// <summary>Field number for the "serial" field.</summary>
    public const int SerialFieldNumber = 7;
    private uint serial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Serial {
      get { return serial_; }
      set {
        serial_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 8;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isCorpse" field.</summary>
    public const int IsCorpseFieldNumber = 9;
    private bool isCorpse_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsCorpse {
      get { return isCorpse_; }
      set {
        isCorpse_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcGameObjectData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcGameObjectData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (ScreenX != other.ScreenX) return false;
      if (ScreenY != other.ScreenY) return false;
      if (Distance != other.Distance) return false;
      if (GameX != other.GameX) return false;
      if (GameY != other.GameY) return false;
      if (Serial != other.Serial) return false;
      if (Name != other.Name) return false;
      if (IsCorpse != other.IsCorpse) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (ScreenX != 0) hash ^= ScreenX.GetHashCode();
      if (ScreenY != 0) hash ^= ScreenY.GetHashCode();
      if (Distance != 0) hash ^= Distance.GetHashCode();
      if (GameX != 0) hash ^= GameX.GetHashCode();
      if (GameY != 0) hash ^= GameY.GetHashCode();
      if (Serial != 0) hash ^= Serial.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (IsCorpse != false) hash ^= IsCorpse.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      if (ScreenX != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ScreenX);
      }
      if (ScreenY != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ScreenY);
      }
      if (Distance != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Distance);
      }
      if (GameX != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(GameX);
      }
      if (GameY != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(GameY);
      }
      if (Serial != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(Serial);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (IsCorpse != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsCorpse);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (ScreenX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ScreenX);
      }
      if (ScreenY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ScreenY);
      }
      if (Distance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Distance);
      }
      if (GameX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GameX);
      }
      if (GameY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GameY);
      }
      if (Serial != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Serial);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (IsCorpse != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcGameObjectData other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      if (other.ScreenX != 0) {
        ScreenX = other.ScreenX;
      }
      if (other.ScreenY != 0) {
        ScreenY = other.ScreenY;
      }
      if (other.Distance != 0) {
        Distance = other.Distance;
      }
      if (other.GameX != 0) {
        GameX = other.GameX;
      }
      if (other.GameY != 0) {
        GameY = other.GameY;
      }
      if (other.Serial != 0) {
        Serial = other.Serial;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.IsCorpse != false) {
        IsCorpse = other.IsCorpse;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 16: {
            ScreenX = input.ReadUInt32();
            break;
          }
          case 24: {
            ScreenY = input.ReadUInt32();
            break;
          }
          case 32: {
            Distance = input.ReadUInt32();
            break;
          }
          case 40: {
            GameX = input.ReadUInt32();
            break;
          }
          case 48: {
            GameY = input.ReadUInt32();
            break;
          }
          case 56: {
            Serial = input.ReadUInt32();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
          case 72: {
            IsCorpse = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcGameObjectList : pb::IMessage<GrpcGameObjectList> {
    private static readonly pb::MessageParser<GrpcGameObjectList> _parser = new pb::MessageParser<GrpcGameObjectList>(() => new GrpcGameObjectList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcGameObjectList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcGameObjectList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcGameObjectList(GrpcGameObjectList other) : this() {
      gameObject_ = other.gameObject_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcGameObjectList Clone() {
      return new GrpcGameObjectList(this);
    }

    /// <summary>Field number for the "gameObject" field.</summary>
    public const int GameObjectFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Uoservice.GrpcGameObjectData> _repeated_gameObject_codec
        = pb::FieldCodec.ForMessage(10, global::Uoservice.GrpcGameObjectData.Parser);
    private readonly pbc::RepeatedField<global::Uoservice.GrpcGameObjectData> gameObject_ = new pbc::RepeatedField<global::Uoservice.GrpcGameObjectData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Uoservice.GrpcGameObjectData> GameObject {
      get { return gameObject_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcGameObjectList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcGameObjectList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!gameObject_.Equals(other.gameObject_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= gameObject_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      gameObject_.WriteTo(output, _repeated_gameObject_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += gameObject_.CalculateSize(_repeated_gameObject_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcGameObjectList other) {
      if (other == null) {
        return;
      }
      gameObject_.Add(other.gameObject_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            gameObject_.AddEntriesFrom(input, _repeated_gameObject_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SemaphoreAction : pb::IMessage<SemaphoreAction> {
    private static readonly pb::MessageParser<SemaphoreAction> _parser = new pb::MessageParser<SemaphoreAction>(() => new SemaphoreAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SemaphoreAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SemaphoreAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SemaphoreAction(SemaphoreAction other) : this() {
      mode_ = other.mode_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SemaphoreAction Clone() {
      return new SemaphoreAction(this);
    }

    /// <summary>Field number for the "mode" field.</summary>
    public const int ModeFieldNumber = 1;
    private string mode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mode {
      get { return mode_; }
      set {
        mode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SemaphoreAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SemaphoreAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Mode != other.Mode) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Mode.Length != 0) hash ^= Mode.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Mode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Mode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Mode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mode);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SemaphoreAction other) {
      if (other == null) {
        return;
      }
      if (other.Mode.Length != 0) {
        Mode = other.Mode;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Mode = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcMobileList : pb::IMessage<GrpcMobileList> {
    private static readonly pb::MessageParser<GrpcMobileList> _parser = new pb::MessageParser<GrpcMobileList>(() => new GrpcMobileList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcMobileList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcMobileList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcMobileList(GrpcMobileList other) : this() {
      mobile_ = other.mobile_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcMobileList Clone() {
      return new GrpcMobileList(this);
    }

    /// <summary>Field number for the "mobile" field.</summary>
    public const int MobileFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Uoservice.GrpcMobileData> _repeated_mobile_codec
        = pb::FieldCodec.ForMessage(10, global::Uoservice.GrpcMobileData.Parser);
    private readonly pbc::RepeatedField<global::Uoservice.GrpcMobileData> mobile_ = new pbc::RepeatedField<global::Uoservice.GrpcMobileData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Uoservice.GrpcMobileData> Mobile {
      get { return mobile_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcMobileList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcMobileList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!mobile_.Equals(other.mobile_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= mobile_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mobile_.WriteTo(output, _repeated_mobile_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mobile_.CalculateSize(_repeated_mobile_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcMobileList other) {
      if (other == null) {
        return;
      }
      mobile_.Add(other.mobile_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            mobile_.AddEntriesFrom(input, _repeated_mobile_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GrpcItemList : pb::IMessage<GrpcItemList> {
    private static readonly pb::MessageParser<GrpcItemList> _parser = new pb::MessageParser<GrpcItemList>(() => new GrpcItemList());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GrpcItemList> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcItemList() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcItemList(GrpcItemList other) : this() {
      item_ = other.item_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GrpcItemList Clone() {
      return new GrpcItemList(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Uoservice.GrpcItemData> _repeated_item_codec
        = pb::FieldCodec.ForMessage(10, global::Uoservice.GrpcItemData.Parser);
    private readonly pbc::RepeatedField<global::Uoservice.GrpcItemData> item_ = new pbc::RepeatedField<global::Uoservice.GrpcItemData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Uoservice.GrpcItemData> Item {
      get { return item_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GrpcItemList);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GrpcItemList other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!item_.Equals(other.item_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= item_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      item_.WriteTo(output, _repeated_item_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += item_.CalculateSize(_repeated_item_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GrpcItemList other) {
      if (other == null) {
        return;
      }
      item_.Add(other.item_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            item_.AddEntriesFrom(input, _repeated_item_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Config : pb::IMessage<Config> {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config(Config other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerStatus : pb::IMessage<PlayerStatus> {
    private static readonly pb::MessageParser<PlayerStatus> _parser = new pb::MessageParser<PlayerStatus>(() => new PlayerStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerStatus(PlayerStatus other) : this() {
      str_ = other.str_;
      dex_ = other.dex_;
      intell_ = other.intell_;
      hits_ = other.hits_;
      hitsMax_ = other.hitsMax_;
      stamina_ = other.stamina_;
      staminaMax_ = other.staminaMax_;
      mana_ = other.mana_;
      manaMax_ = other.manaMax_;
      gold_ = other.gold_;
      physicalResistance_ = other.physicalResistance_;
      weight_ = other.weight_;
      weightMax_ = other.weightMax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerStatus Clone() {
      return new PlayerStatus(this);
    }

    /// <summary>Field number for the "str" field.</summary>
    public const int StrFieldNumber = 1;
    private uint str_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Str {
      get { return str_; }
      set {
        str_ = value;
      }
    }

    /// <summary>Field number for the "dex" field.</summary>
    public const int DexFieldNumber = 2;
    private uint dex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Dex {
      get { return dex_; }
      set {
        dex_ = value;
      }
    }

    /// <summary>Field number for the "intell" field.</summary>
    public const int IntellFieldNumber = 3;
    private uint intell_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Intell {
      get { return intell_; }
      set {
        intell_ = value;
      }
    }

    /// <summary>Field number for the "hits" field.</summary>
    public const int HitsFieldNumber = 4;
    private uint hits_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Hits {
      get { return hits_; }
      set {
        hits_ = value;
      }
    }

    /// <summary>Field number for the "hitsMax" field.</summary>
    public const int HitsMaxFieldNumber = 5;
    private uint hitsMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint HitsMax {
      get { return hitsMax_; }
      set {
        hitsMax_ = value;
      }
    }

    /// <summary>Field number for the "stamina" field.</summary>
    public const int StaminaFieldNumber = 6;
    private uint stamina_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Stamina {
      get { return stamina_; }
      set {
        stamina_ = value;
      }
    }

    /// <summary>Field number for the "staminaMax" field.</summary>
    public const int StaminaMaxFieldNumber = 7;
    private uint staminaMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint StaminaMax {
      get { return staminaMax_; }
      set {
        staminaMax_ = value;
      }
    }

    /// <summary>Field number for the "mana" field.</summary>
    public const int ManaFieldNumber = 8;
    private uint mana_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Mana {
      get { return mana_; }
      set {
        mana_ = value;
      }
    }

    /// <summary>Field number for the "manaMax" field.</summary>
    public const int ManaMaxFieldNumber = 9;
    private uint manaMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ManaMax {
      get { return manaMax_; }
      set {
        manaMax_ = value;
      }
    }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 10;
    private uint gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    /// <summary>Field number for the "physicalResistance" field.</summary>
    public const int PhysicalResistanceFieldNumber = 11;
    private uint physicalResistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PhysicalResistance {
      get { return physicalResistance_; }
      set {
        physicalResistance_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 12;
    private uint weight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Weight {
      get { return weight_; }
      set {
        weight_ = value;
      }
    }

    /// <summary>Field number for the "weightMax" field.</summary>
    public const int WeightMaxFieldNumber = 13;
    private uint weightMax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint WeightMax {
      get { return weightMax_; }
      set {
        weightMax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Str != other.Str) return false;
      if (Dex != other.Dex) return false;
      if (Intell != other.Intell) return false;
      if (Hits != other.Hits) return false;
      if (HitsMax != other.HitsMax) return false;
      if (Stamina != other.Stamina) return false;
      if (StaminaMax != other.StaminaMax) return false;
      if (Mana != other.Mana) return false;
      if (ManaMax != other.ManaMax) return false;
      if (Gold != other.Gold) return false;
      if (PhysicalResistance != other.PhysicalResistance) return false;
      if (Weight != other.Weight) return false;
      if (WeightMax != other.WeightMax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Str != 0) hash ^= Str.GetHashCode();
      if (Dex != 0) hash ^= Dex.GetHashCode();
      if (Intell != 0) hash ^= Intell.GetHashCode();
      if (Hits != 0) hash ^= Hits.GetHashCode();
      if (HitsMax != 0) hash ^= HitsMax.GetHashCode();
      if (Stamina != 0) hash ^= Stamina.GetHashCode();
      if (StaminaMax != 0) hash ^= StaminaMax.GetHashCode();
      if (Mana != 0) hash ^= Mana.GetHashCode();
      if (ManaMax != 0) hash ^= ManaMax.GetHashCode();
      if (Gold != 0) hash ^= Gold.GetHashCode();
      if (PhysicalResistance != 0) hash ^= PhysicalResistance.GetHashCode();
      if (Weight != 0) hash ^= Weight.GetHashCode();
      if (WeightMax != 0) hash ^= WeightMax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Str != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Str);
      }
      if (Dex != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Dex);
      }
      if (Intell != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Intell);
      }
      if (Hits != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Hits);
      }
      if (HitsMax != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(HitsMax);
      }
      if (Stamina != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Stamina);
      }
      if (StaminaMax != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(StaminaMax);
      }
      if (Mana != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(Mana);
      }
      if (ManaMax != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(ManaMax);
      }
      if (Gold != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(Gold);
      }
      if (PhysicalResistance != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(PhysicalResistance);
      }
      if (Weight != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(Weight);
      }
      if (WeightMax != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(WeightMax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Str != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Str);
      }
      if (Dex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dex);
      }
      if (Intell != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Intell);
      }
      if (Hits != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Hits);
      }
      if (HitsMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HitsMax);
      }
      if (Stamina != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Stamina);
      }
      if (StaminaMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StaminaMax);
      }
      if (Mana != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Mana);
      }
      if (ManaMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ManaMax);
      }
      if (Gold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Gold);
      }
      if (PhysicalResistance != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PhysicalResistance);
      }
      if (Weight != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Weight);
      }
      if (WeightMax != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WeightMax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerStatus other) {
      if (other == null) {
        return;
      }
      if (other.Str != 0) {
        Str = other.Str;
      }
      if (other.Dex != 0) {
        Dex = other.Dex;
      }
      if (other.Intell != 0) {
        Intell = other.Intell;
      }
      if (other.Hits != 0) {
        Hits = other.Hits;
      }
      if (other.HitsMax != 0) {
        HitsMax = other.HitsMax;
      }
      if (other.Stamina != 0) {
        Stamina = other.Stamina;
      }
      if (other.StaminaMax != 0) {
        StaminaMax = other.StaminaMax;
      }
      if (other.Mana != 0) {
        Mana = other.Mana;
      }
      if (other.ManaMax != 0) {
        ManaMax = other.ManaMax;
      }
      if (other.Gold != 0) {
        Gold = other.Gold;
      }
      if (other.PhysicalResistance != 0) {
        PhysicalResistance = other.PhysicalResistance;
      }
      if (other.Weight != 0) {
        Weight = other.Weight;
      }
      if (other.WeightMax != 0) {
        WeightMax = other.WeightMax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Str = input.ReadUInt32();
            break;
          }
          case 16: {
            Dex = input.ReadUInt32();
            break;
          }
          case 24: {
            Intell = input.ReadUInt32();
            break;
          }
          case 32: {
            Hits = input.ReadUInt32();
            break;
          }
          case 40: {
            HitsMax = input.ReadUInt32();
            break;
          }
          case 48: {
            Stamina = input.ReadUInt32();
            break;
          }
          case 56: {
            StaminaMax = input.ReadUInt32();
            break;
          }
          case 64: {
            Mana = input.ReadUInt32();
            break;
          }
          case 72: {
            ManaMax = input.ReadUInt32();
            break;
          }
          case 80: {
            Gold = input.ReadUInt32();
            break;
          }
          case 88: {
            PhysicalResistance = input.ReadUInt32();
            break;
          }
          case 96: {
            Weight = input.ReadUInt32();
            break;
          }
          case 104: {
            WeightMax = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class States : pb::IMessage<States> {
    private static readonly pb::MessageParser<States> _parser = new pb::MessageParser<States>(() => new States());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<States> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public States() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public States(States other) : this() {
      mobileList_ = other.mobileList_ != null ? other.mobileList_.Clone() : null;
      worldItemList_ = other.worldItemList_ != null ? other.worldItemList_.Clone() : null;
      equippedItemList_ = other.equippedItemList_ != null ? other.equippedItemList_.Clone() : null;
      backpackItemList_ = other.backpackItemList_ != null ? other.backpackItemList_.Clone() : null;
      playerStatus_ = other.playerStatus_ != null ? other.playerStatus_.Clone() : null;
      mobileObjectList_ = other.mobileObjectList_ != null ? other.mobileObjectList_.Clone() : null;
      playerMobileObjectList_ = other.playerMobileObjectList_ != null ? other.playerMobileObjectList_.Clone() : null;
      landObjectList_ = other.landObjectList_ != null ? other.landObjectList_.Clone() : null;
      itemObjectList_ = other.itemObjectList_ != null ? other.itemObjectList_.Clone() : null;
      staticObjectList_ = other.staticObjectList_ != null ? other.staticObjectList_.Clone() : null;
      itemDropableLandList_ = other.itemDropableLandList_ != null ? other.itemDropableLandList_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public States Clone() {
      return new States(this);
    }

    /// <summary>Field number for the "mobileList" field.</summary>
    public const int MobileListFieldNumber = 1;
    private global::Uoservice.GrpcMobileList mobileList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcMobileList MobileList {
      get { return mobileList_; }
      set {
        mobileList_ = value;
      }
    }

    /// <summary>Field number for the "worldItemList" field.</summary>
    public const int WorldItemListFieldNumber = 2;
    private global::Uoservice.GrpcItemList worldItemList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcItemList WorldItemList {
      get { return worldItemList_; }
      set {
        worldItemList_ = value;
      }
    }

    /// <summary>Field number for the "equippedItemList" field.</summary>
    public const int EquippedItemListFieldNumber = 3;
    private global::Uoservice.GrpcItemList equippedItemList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcItemList EquippedItemList {
      get { return equippedItemList_; }
      set {
        equippedItemList_ = value;
      }
    }

    /// <summary>Field number for the "backpackItemList" field.</summary>
    public const int BackpackItemListFieldNumber = 4;
    private global::Uoservice.GrpcItemList backpackItemList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcItemList BackpackItemList {
      get { return backpackItemList_; }
      set {
        backpackItemList_ = value;
      }
    }

    /// <summary>Field number for the "playerStatus" field.</summary>
    public const int PlayerStatusFieldNumber = 5;
    private global::Uoservice.PlayerStatus playerStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.PlayerStatus PlayerStatus {
      get { return playerStatus_; }
      set {
        playerStatus_ = value;
      }
    }

    /// <summary>Field number for the "mobileObjectList" field.</summary>
    public const int MobileObjectListFieldNumber = 6;
    private global::Uoservice.GrpcGameObjectList mobileObjectList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcGameObjectList MobileObjectList {
      get { return mobileObjectList_; }
      set {
        mobileObjectList_ = value;
      }
    }

    /// <summary>Field number for the "playerMobileObjectList" field.</summary>
    public const int PlayerMobileObjectListFieldNumber = 7;
    private global::Uoservice.GrpcGameObjectList playerMobileObjectList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcGameObjectList PlayerMobileObjectList {
      get { return playerMobileObjectList_; }
      set {
        playerMobileObjectList_ = value;
      }
    }

    /// <summary>Field number for the "landObjectList" field.</summary>
    public const int LandObjectListFieldNumber = 8;
    private global::Uoservice.GrpcGameObjectList landObjectList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcGameObjectList LandObjectList {
      get { return landObjectList_; }
      set {
        landObjectList_ = value;
      }
    }

    /// <summary>Field number for the "itemObjectList" field.</summary>
    public const int ItemObjectListFieldNumber = 9;
    private global::Uoservice.GrpcGameObjectList itemObjectList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcGameObjectList ItemObjectList {
      get { return itemObjectList_; }
      set {
        itemObjectList_ = value;
      }
    }

    /// <summary>Field number for the "staticObjectList" field.</summary>
    public const int StaticObjectListFieldNumber = 10;
    private global::Uoservice.GrpcGameObjectList staticObjectList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcGameObjectList StaticObjectList {
      get { return staticObjectList_; }
      set {
        staticObjectList_ = value;
      }
    }

    /// <summary>Field number for the "itemDropableLandList" field.</summary>
    public const int ItemDropableLandListFieldNumber = 11;
    private global::Uoservice.GrpcGameObjectList itemDropableLandList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.GrpcGameObjectList ItemDropableLandList {
      get { return itemDropableLandList_; }
      set {
        itemDropableLandList_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as States);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(States other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(MobileList, other.MobileList)) return false;
      if (!object.Equals(WorldItemList, other.WorldItemList)) return false;
      if (!object.Equals(EquippedItemList, other.EquippedItemList)) return false;
      if (!object.Equals(BackpackItemList, other.BackpackItemList)) return false;
      if (!object.Equals(PlayerStatus, other.PlayerStatus)) return false;
      if (!object.Equals(MobileObjectList, other.MobileObjectList)) return false;
      if (!object.Equals(PlayerMobileObjectList, other.PlayerMobileObjectList)) return false;
      if (!object.Equals(LandObjectList, other.LandObjectList)) return false;
      if (!object.Equals(ItemObjectList, other.ItemObjectList)) return false;
      if (!object.Equals(StaticObjectList, other.StaticObjectList)) return false;
      if (!object.Equals(ItemDropableLandList, other.ItemDropableLandList)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (mobileList_ != null) hash ^= MobileList.GetHashCode();
      if (worldItemList_ != null) hash ^= WorldItemList.GetHashCode();
      if (equippedItemList_ != null) hash ^= EquippedItemList.GetHashCode();
      if (backpackItemList_ != null) hash ^= BackpackItemList.GetHashCode();
      if (playerStatus_ != null) hash ^= PlayerStatus.GetHashCode();
      if (mobileObjectList_ != null) hash ^= MobileObjectList.GetHashCode();
      if (playerMobileObjectList_ != null) hash ^= PlayerMobileObjectList.GetHashCode();
      if (landObjectList_ != null) hash ^= LandObjectList.GetHashCode();
      if (itemObjectList_ != null) hash ^= ItemObjectList.GetHashCode();
      if (staticObjectList_ != null) hash ^= StaticObjectList.GetHashCode();
      if (itemDropableLandList_ != null) hash ^= ItemDropableLandList.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mobileList_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MobileList);
      }
      if (worldItemList_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(WorldItemList);
      }
      if (equippedItemList_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(EquippedItemList);
      }
      if (backpackItemList_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BackpackItemList);
      }
      if (playerStatus_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PlayerStatus);
      }
      if (mobileObjectList_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(MobileObjectList);
      }
      if (playerMobileObjectList_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(PlayerMobileObjectList);
      }
      if (landObjectList_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(LandObjectList);
      }
      if (itemObjectList_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(ItemObjectList);
      }
      if (staticObjectList_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(StaticObjectList);
      }
      if (itemDropableLandList_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(ItemDropableLandList);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mobileList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MobileList);
      }
      if (worldItemList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WorldItemList);
      }
      if (equippedItemList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EquippedItemList);
      }
      if (backpackItemList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BackpackItemList);
      }
      if (playerStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerStatus);
      }
      if (mobileObjectList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MobileObjectList);
      }
      if (playerMobileObjectList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerMobileObjectList);
      }
      if (landObjectList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LandObjectList);
      }
      if (itemObjectList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemObjectList);
      }
      if (staticObjectList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StaticObjectList);
      }
      if (itemDropableLandList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ItemDropableLandList);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(States other) {
      if (other == null) {
        return;
      }
      if (other.mobileList_ != null) {
        if (mobileList_ == null) {
          mobileList_ = new global::Uoservice.GrpcMobileList();
        }
        MobileList.MergeFrom(other.MobileList);
      }
      if (other.worldItemList_ != null) {
        if (worldItemList_ == null) {
          worldItemList_ = new global::Uoservice.GrpcItemList();
        }
        WorldItemList.MergeFrom(other.WorldItemList);
      }
      if (other.equippedItemList_ != null) {
        if (equippedItemList_ == null) {
          equippedItemList_ = new global::Uoservice.GrpcItemList();
        }
        EquippedItemList.MergeFrom(other.EquippedItemList);
      }
      if (other.backpackItemList_ != null) {
        if (backpackItemList_ == null) {
          backpackItemList_ = new global::Uoservice.GrpcItemList();
        }
        BackpackItemList.MergeFrom(other.BackpackItemList);
      }
      if (other.playerStatus_ != null) {
        if (playerStatus_ == null) {
          playerStatus_ = new global::Uoservice.PlayerStatus();
        }
        PlayerStatus.MergeFrom(other.PlayerStatus);
      }
      if (other.mobileObjectList_ != null) {
        if (mobileObjectList_ == null) {
          mobileObjectList_ = new global::Uoservice.GrpcGameObjectList();
        }
        MobileObjectList.MergeFrom(other.MobileObjectList);
      }
      if (other.playerMobileObjectList_ != null) {
        if (playerMobileObjectList_ == null) {
          playerMobileObjectList_ = new global::Uoservice.GrpcGameObjectList();
        }
        PlayerMobileObjectList.MergeFrom(other.PlayerMobileObjectList);
      }
      if (other.landObjectList_ != null) {
        if (landObjectList_ == null) {
          landObjectList_ = new global::Uoservice.GrpcGameObjectList();
        }
        LandObjectList.MergeFrom(other.LandObjectList);
      }
      if (other.itemObjectList_ != null) {
        if (itemObjectList_ == null) {
          itemObjectList_ = new global::Uoservice.GrpcGameObjectList();
        }
        ItemObjectList.MergeFrom(other.ItemObjectList);
      }
      if (other.staticObjectList_ != null) {
        if (staticObjectList_ == null) {
          staticObjectList_ = new global::Uoservice.GrpcGameObjectList();
        }
        StaticObjectList.MergeFrom(other.StaticObjectList);
      }
      if (other.itemDropableLandList_ != null) {
        if (itemDropableLandList_ == null) {
          itemDropableLandList_ = new global::Uoservice.GrpcGameObjectList();
        }
        ItemDropableLandList.MergeFrom(other.ItemDropableLandList);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (mobileList_ == null) {
              mobileList_ = new global::Uoservice.GrpcMobileList();
            }
            input.ReadMessage(mobileList_);
            break;
          }
          case 18: {
            if (worldItemList_ == null) {
              worldItemList_ = new global::Uoservice.GrpcItemList();
            }
            input.ReadMessage(worldItemList_);
            break;
          }
          case 26: {
            if (equippedItemList_ == null) {
              equippedItemList_ = new global::Uoservice.GrpcItemList();
            }
            input.ReadMessage(equippedItemList_);
            break;
          }
          case 34: {
            if (backpackItemList_ == null) {
              backpackItemList_ = new global::Uoservice.GrpcItemList();
            }
            input.ReadMessage(backpackItemList_);
            break;
          }
          case 42: {
            if (playerStatus_ == null) {
              playerStatus_ = new global::Uoservice.PlayerStatus();
            }
            input.ReadMessage(playerStatus_);
            break;
          }
          case 50: {
            if (mobileObjectList_ == null) {
              mobileObjectList_ = new global::Uoservice.GrpcGameObjectList();
            }
            input.ReadMessage(mobileObjectList_);
            break;
          }
          case 58: {
            if (playerMobileObjectList_ == null) {
              playerMobileObjectList_ = new global::Uoservice.GrpcGameObjectList();
            }
            input.ReadMessage(playerMobileObjectList_);
            break;
          }
          case 66: {
            if (landObjectList_ == null) {
              landObjectList_ = new global::Uoservice.GrpcGameObjectList();
            }
            input.ReadMessage(landObjectList_);
            break;
          }
          case 74: {
            if (itemObjectList_ == null) {
              itemObjectList_ = new global::Uoservice.GrpcGameObjectList();
            }
            input.ReadMessage(itemObjectList_);
            break;
          }
          case 82: {
            if (staticObjectList_ == null) {
              staticObjectList_ = new global::Uoservice.GrpcGameObjectList();
            }
            input.ReadMessage(staticObjectList_);
            break;
          }
          case 90: {
            if (itemDropableLandList_ == null) {
              itemDropableLandList_ = new global::Uoservice.GrpcGameObjectList();
            }
            input.ReadMessage(itemDropableLandList_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class WalkDirection : pb::IMessage<WalkDirection> {
    private static readonly pb::MessageParser<WalkDirection> _parser = new pb::MessageParser<WalkDirection>(() => new WalkDirection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WalkDirection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WalkDirection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WalkDirection(WalkDirection other) : this() {
      direction_ = other.direction_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WalkDirection Clone() {
      return new WalkDirection(this);
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 1;
    private uint direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WalkDirection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WalkDirection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Direction != other.Direction) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Direction != 0) hash ^= Direction.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Direction != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Direction);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Direction != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Direction);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WalkDirection other) {
      if (other == null) {
        return;
      }
      if (other.Direction != 0) {
        Direction = other.Direction;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Direction = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Actions : pb::IMessage<Actions> {
    private static readonly pb::MessageParser<Actions> _parser = new pb::MessageParser<Actions>(() => new Actions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Actions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Uoservice.UoServiceReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Actions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Actions(Actions other) : this() {
      actionType_ = other.actionType_;
      mobileSerial_ = other.mobileSerial_;
      itemSerial_ = other.itemSerial_;
      walkDirection_ = other.walkDirection_ != null ? other.walkDirection_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Actions Clone() {
      return new Actions(this);
    }

    /// <summary>Field number for the "actionType" field.</summary>
    public const int ActionTypeFieldNumber = 1;
    private uint actionType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ActionType {
      get { return actionType_; }
      set {
        actionType_ = value;
      }
    }

    /// <summary>Field number for the "mobileSerial" field.</summary>
    public const int MobileSerialFieldNumber = 2;
    private uint mobileSerial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint MobileSerial {
      get { return mobileSerial_; }
      set {
        mobileSerial_ = value;
      }
    }

    /// <summary>Field number for the "itemSerial" field.</summary>
    public const int ItemSerialFieldNumber = 3;
    private uint itemSerial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ItemSerial {
      get { return itemSerial_; }
      set {
        itemSerial_ = value;
      }
    }

    /// <summary>Field number for the "walkDirection" field.</summary>
    public const int WalkDirectionFieldNumber = 4;
    private global::Uoservice.WalkDirection walkDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Uoservice.WalkDirection WalkDirection {
      get { return walkDirection_; }
      set {
        walkDirection_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Actions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Actions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ActionType != other.ActionType) return false;
      if (MobileSerial != other.MobileSerial) return false;
      if (ItemSerial != other.ItemSerial) return false;
      if (!object.Equals(WalkDirection, other.WalkDirection)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ActionType != 0) hash ^= ActionType.GetHashCode();
      if (MobileSerial != 0) hash ^= MobileSerial.GetHashCode();
      if (ItemSerial != 0) hash ^= ItemSerial.GetHashCode();
      if (walkDirection_ != null) hash ^= WalkDirection.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ActionType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ActionType);
      }
      if (MobileSerial != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MobileSerial);
      }
      if (ItemSerial != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(ItemSerial);
      }
      if (walkDirection_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(WalkDirection);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ActionType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ActionType);
      }
      if (MobileSerial != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MobileSerial);
      }
      if (ItemSerial != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemSerial);
      }
      if (walkDirection_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WalkDirection);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Actions other) {
      if (other == null) {
        return;
      }
      if (other.ActionType != 0) {
        ActionType = other.ActionType;
      }
      if (other.MobileSerial != 0) {
        MobileSerial = other.MobileSerial;
      }
      if (other.ItemSerial != 0) {
        ItemSerial = other.ItemSerial;
      }
      if (other.walkDirection_ != null) {
        if (walkDirection_ == null) {
          walkDirection_ = new global::Uoservice.WalkDirection();
        }
        WalkDirection.MergeFrom(other.WalkDirection);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ActionType = input.ReadUInt32();
            break;
          }
          case 16: {
            MobileSerial = input.ReadUInt32();
            break;
          }
          case 24: {
            ItemSerial = input.ReadUInt32();
            break;
          }
          case 34: {
            if (walkDirection_ == null) {
              walkDirection_ = new global::Uoservice.WalkDirection();
            }
            input.ReadMessage(walkDirection_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
