// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UoService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Uoservice {
  public static partial class UoService
  {
    static readonly string __ServiceName = "uoservice.UoService";

    static readonly grpc::Marshaller<global::Uoservice.ImageRequest> __Marshaller_uoservice_ImageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Uoservice.ImageRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Uoservice.ImageResponse> __Marshaller_uoservice_ImageResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Uoservice.ImageResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Uoservice.Actions> __Marshaller_uoservice_Actions = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Uoservice.Actions.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Uoservice.Empty> __Marshaller_uoservice_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Uoservice.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse> __Method_reset = new grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "reset",
        __Marshaller_uoservice_ImageRequest,
        __Marshaller_uoservice_ImageResponse);

    static readonly grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse> __Method_step = new grpc::Method<global::Uoservice.ImageRequest, global::Uoservice.ImageResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "step",
        __Marshaller_uoservice_ImageRequest,
        __Marshaller_uoservice_ImageResponse);

    static readonly grpc::Method<global::Uoservice.Actions, global::Uoservice.Empty> __Method_act = new grpc::Method<global::Uoservice.Actions, global::Uoservice.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "act",
        __Marshaller_uoservice_Actions,
        __Marshaller_uoservice_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Uoservice.UoServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UoService</summary>
    public abstract partial class UoServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Uoservice.ImageResponse> reset(global::Uoservice.ImageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Uoservice.ImageResponse> step(global::Uoservice.ImageRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Uoservice.Empty> act(global::Uoservice.Actions request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UoService</summary>
    public partial class UoServiceClient : grpc::ClientBase<UoServiceClient>
    {
      /// <summary>Creates a new client for UoService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UoServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UoService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UoServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UoServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UoServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Uoservice.ImageResponse reset(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return reset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Uoservice.ImageResponse reset(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_reset, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> resetAsync(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return resetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> resetAsync(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_reset, null, options, request);
      }
      public virtual global::Uoservice.ImageResponse step(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return step(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Uoservice.ImageResponse step(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_step, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> stepAsync(global::Uoservice.ImageRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return stepAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.ImageResponse> stepAsync(global::Uoservice.ImageRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_step, null, options, request);
      }
      public virtual global::Uoservice.Empty act(global::Uoservice.Actions request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return act(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Uoservice.Empty act(global::Uoservice.Actions request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_act, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.Empty> actAsync(global::Uoservice.Actions request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return actAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Uoservice.Empty> actAsync(global::Uoservice.Actions request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_act, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UoServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UoServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UoServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_reset, serviceImpl.reset)
          .AddMethod(__Method_step, serviceImpl.step)
          .AddMethod(__Method_act, serviceImpl.act).Build();
    }

  }
}
#endregion
